In [2]:
import pandas as pd

# Caso 1

# 1. Caso: Análisis de la Copa Mundial Femenina

## 1.1 Contexto

La Copa Mundial Femenina de la FIFA ha experimentado un crecimiento exponencial desde su primera edición en 1991, atrayendo una audiencia global y consolidando el fútbol femenino como un pilar del deporte internacional. Con la evolución del torneo, ha surgido la necesidad de analizar tendencias en el desempeño de las selecciones, patrones de juego y factores que contribuyen al éxito en la competición.

La FIFA está interesada en un análisis detallado del rendimiento de los equipos en las distintas ediciones del torneo, identificando
patrones en la cantidad de goles, frecuencia de victorias y desempeño a lo largo de los años. Se busca descubrir qué selecciones
han dominado históricamente y cómo ha evolucionado el nivel de competitividad

A través del análisis de datos de partidos de la Copa Mundial Femenina desde 1991 hasta 2023, se espera:
- Identificar tendencias de goles y resultados a lo largo de los torneos.

- Determinar los equipos con mayor rendimiento en cada edición.
- Explorar patrones de juego y evolución del fútbol femenino a nivel internacional.

Para esto, se cuenta con los siguientes datasets:

In [3]:
wc=pd.read_csv('https://raw.githubusercontent.com/daramireh/simonBolivarCienciaDatos/refs/heads/main/world_cup_women.csv')
matches=pd.read_csv('https://raw.githubusercontent.com/daramireh/simonBolivarCienciaDatos/refs/heads/main/matches_1991_2023.csv')

In [3]:
wc

,Year,Host,Teams,Champion,Runner-Up,TopScorrer,Attendance,AttendanceAvg,Matches
0,2023,"Australia, New Zealand",32,NaN,NaN,Hinata Miyazawa - 5,1976274,30879,64
1,2019,France,24,United States,Netherlands,"Alex Morgan, Megan Rapinoe... - 6",1095118,21902,52
2,2015,Canada,24,United States,Japan,"Célia Šašić, Carli Lloyd - 6",1353486,26029,52
3,2011,Germany,16,Japan,United States,Homare Sawa - 5,248107,31013,32
4,2007,China PR,16,Germany,Brazil,Marta - 7,1176955,36780,32
5,2003,United States,16,Germany,Sweden,Birgit Prinz - 7,656789,20525,32
6,1999,United States,16,United States,China PR,"Sun Wen, Sissi - 7",1214215,37944,32
7,1995,Sweden,12,Norway,Germany,Ann Kristin Aarønes - 6,112294,4319,26
8,1991,China PR,12,United States,Norway,Michelle Akers - 10,515000,19808,26

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
matches.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,away_manager,away_captain,Attendance,Venue,Officials,Round,Date,Score,Referee,Notes,Host,Year,home_goal,away_goal,home_goal_long,away_goal_long,home_own_goal,away_own_goal,home_penalty_goal,away_penalty_goal,home_penalty_miss_long,away_penalty_miss_long,home_penalty_shootout_goal_long,away_penalty_shootout_goal_long,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Spain,England,1,2.1,NaN,0,0.5,NaN,Jorge Vilda,Olga Carmona,Sarina Wiegman,Millie Bright,75784,"Accor Stadium, Sydney",Tori Penso (Referee) · Brooke Mayo (AR1) · Kat...,Final,2023-08-20,1–0,Tori Penso,NaN,"Australia, New Zealand",2023,Olga Carmona · 29’,NaN,['29’|1:0|Olga Carmona|Assist:|Mariona Caldent...,NaN,NaN,NaN,NaN,NaN,['69’|1:0|Jennifer Hermoso|Penalty saved by Ma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['78’|1:0|Salma Paralluelo'],['55’|1:0|Lauren Hemp'],"['60’|1:0|Oihane Hernández|for Alba Redondo', ...","['46’|1:0|Lauren James|for Alessia Russo', '46..."
1,Sweden,Australia,2,1.8,NaN,0,0.8,NaN,Peter Gerhardsson,Kosovare Asllani,Tony Gustavsson,Sam Kerr,49461,"Suncorp Stadium, Brisbane",NaN,Third-place match,2023-08-19,2–0,NaN,NaN,"Australia, New Zealand",2023,Kosovare Asllani · 62’,NaN,['62’|2:0|Kosovare Asllani|Assist:|Stina Black...,NaN,NaN,NaN,Fridolina Rolfö (P) · 30’,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['88’|2:0|Elin Rubensson', '90+5’|2:0|Lina Hur...",['45+1’|1:0|Katrina Gorry'],['67’|2:0|Rebecka Blomqvist|for Stina Blackste...,"['60’|1:0|Cortnee Vine|for Hayley Raso', '60’|..."
2,Australia,England,1,1.4,NaN,3,1.3,NaN,Tony Gustavsson,Sam Kerr,Sarina Wiegman,Millie Bright,75784,"Accor Stadium, Sydney",Tori Penso (Referee) · Brooke Mayo (AR1) · Mij...,Semi-finals,2023-08-16,1–3,Tori Penso,NaN,"Australia, New Zealand",2023,Sam Kerr · 63’,Ella Toone · 36’|Lauren Hemp · 71’|Alessia Rus...,['63’|1:1|Sam Kerr|Assist:|Katrina Gorry'],"['36’|0:1|Ella Toone', '71’|1:2|Lauren Hemp|As...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['10’|0:0|Alex Greenwood', '90+5’|1:3|Chloe Ke...","['72’|1:2|Cortnee Vine|for Hayley Raso', '81’|...","['87’|1:3|Chloe Kelly|for Alessia Russo', '90’..."
3,Spain,Sweden,2,1.6,NaN,1,0.9,NaN,Jorge Vilda,Olga Carmona,Peter Gerhardsson,Kosovare Asllani,43217,"Eden Park, Auckland",Edina Alves Batista (Referee) · Neuza Back (AR...,Semi-finals,2023-08-15,2–1,Edina Alves Batista,NaN,"Australia, New Zealand",2023,Salma Paralluelo · 81’|Olga Carmona · 89’,Rebecka Blomqvist · 88’,"['81’|1:0|Salma Paralluelo', '89’|2:1|Olga Car...",['88’|1:1|Rebecka Blomqvist|Assist:|Lina Hurtig'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['57’|0:0|Salma Paralluelo|for Alexia Putellas...,['77’|0:0|Rebecka Blomqvist|for Stina Blackste...
4,Australia,France,0,1.6,7.0,0,2.0,6.0,Tony Gustavsson,Steph Catley,Hervé Renard,Wendie Renard,49461,"Suncorp Stadium, Brisbane",María Carvajal (Referee) · Leslie Vásquez (AR1...,Quarter-finals,2023-08-12,(7) 0–0 (6),María Carvajal,Australia won on penalty kicks following extra...,"Australia, New Zealand",2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['2|1:0|Caitlin Foord', '6|2:2|Sam Kerr', '8|3...","['3|1:1|Kadidiatou Diani', '5|1:2|Wendie Renar...","['4|1:1|Steph Catley', '10|3:3|Mackenzie Arnol...","['1|0:0|Selma Bacha', '9|3:3|Ève Périsset', '1...",NaN,NaN,NaN,NaN,['92’|0:0|Katrina Gorry'],NaN,"['55’|0:0|Sam Kerr|for Emily van Egmond', '104...","['64’|0:0|Vicki Bècho|for Sandie Toletti', '12..."

El primer dataset nos da información relevante sobre todas las copas del mundo realizadas hasta el momento, de 1991 a 2023, con datos como su sede, la cantidad de partidos jugados, la cantidad de equipos participantes, el promedio de asistencia por partido, entre otras variables.

Por otro lado el segundo dataset ofrece datos más a fondo de cada mundial, ya que este contiene la información partido a partido de todos los partidos que se han jugado en las copas del mundo femeninas, con variables que nos cuentan el resultado de cada partido, los equipos involucrados, las goleadoras, las amonestaciones por equipo, el número de asistentes por partido, entre otras variables útiles para el análisis.

## 1.2 Análisis de nulos y variables de los datasets

Como vimos en la visualización de los datasets, el dataframe `wc` correspondiente a la informacion general de los mundiales, no contiene valores faltantes, salvo por las variables de campeón y subcampeón de la edición del 2023, los cuales son España e Inglaterra respectivamente.

Pasando al análisis del segundo dataset, con el dataframe `matches`, veamos los tipos de variables y valores nulos del mismo.

In [6]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        348 non-null    object
 1   away_team                        348 non-null    object
 2   home_score                       348 non-null    int64
 3   home_xg                          116 non-null    float64
 4   home_penalty                     11 non-null     float64
 5   away_score                       348 non-null    int64
 6   away_xg                          116 non-null    float64
 7   away_penalty                     11 non-null     float64
 8   home_manager                     168 non-null    object
 9   home_captain                     168 non-null    object
 10  away_manager                     168 non-null    object
 11  away_captain                     168 non-null    object
 12  Attendance                       348 non-null    int64
 13  Venue                            348 non-null    object
 14  Officials                        345 non-null    object
 15  Round                            348 non-null    object
 16  Date                             348 non-null    object
 17  Score                            348 non-null    object
 18  Referee                          341 non-null    object
 19  Notes                            20 non-null     object
 20  Host                             348 non-null    object
 21  Year                             348 non-null    int64
 22  home_goal                        252 non-null    object
 23  away_goal                        200 non-null    object
 24  home_goal_long                   252 non-null    object
 25  away_goal_long                   200 non-null    object
 26  home_own_goal                    18 non-null     object
 27  away_own_goal                    13 non-null     object
 28  home_penalty_goal                54 non-null     object
 29  away_penalty_goal                35 non-null     object
 30  home_penalty_miss_long           13 non-null     object
 31  away_penalty_miss_long           7 non-null      object
 32  home_penalty_shootout_goal_long  11 non-null     object
 33  away_penalty_shootout_goal_long  11 non-null     object
 34  home_penalty_shootout_miss_long  8 non-null      object
 35  away_penalty_shootout_miss_long  10 non-null     object
 36  home_red_card                    8 non-null      object
 37  away_red_card                    11 non-null     object
 38  home_yellow_red_card             8 non-null      object
 39  away_yellow_red_card             3 non-null      object
 40  home_yellow_card_long            213 non-null    object
 41  away_yellow_card_long            230 non-null    object
 42  home_substitute_in_long          344 non-null    object
 43  away_substitute_in_long          343 non-null    object
dtypes: float64(4), int64(4), object(36)
memory usage: 119.8+ KB

Este ya cuenta con mayor cantidad de valores faltantes, y todo depende de la variable que estemos tratando. Algunas como `home_goal`, que inidica las jugadoras del equipo que ofició como local que metieron gol en un partido en específico, marcan como nulo si el equipo local no marcó ningún gol. Varias variables sufren de esto, pero no es un problema que se deba imputar, simplemente saber que este tipo de variables que miden los goles, las tarjetas rojas, las tarjetas amarillas, los goles de penalti, entre otras, cuando tienen valores faltantes es porque esa jugada o sanción en específico no ocurrió en el partido.

Sin embargo, existen estadísticas como los goles esperados (`home_xg` y `away_xg`) que se empezaron a considerar en años recientes, por lo que en los primeros mundiales esta estadística no existía y se marca como nulo en el dataset. También ocurre que no se tiene registro de partidos antiguos sobre quienes fueron las capitanas y entrenadores de los equipos, por lo que también hay valores faltantes en este tipo de variables.

In [15]:
print(f"Valores nulos por variable en Wc:\n{wc.isnull().sum()}")
print('\n')
print(f"Valores nulos por variable en Matches:\n{matches.isnull().sum()}")

Valores nulos por variable en Wc:
Year             0
Host             0
Teams            0
Champion         1
Runner-Up        1
TopScorrer       0
Attendance       0
AttendanceAvg    0
Matches          0
dtype: int64


Valores nulos por variable en Matches:
home_team                            0
away_team                            0
home_score                           0
home_xg                            232
home_penalty                       337
away_score                           0
away_xg                            232
away_penalty                       337
home_manager                       180
home_captain                       180
away_manager                       180
away_captain                       180
Attendance                           0
Venue                                0
Officials                            3
Round                                0
Date                                 0
Score                                0
Referee                              7
Notes                              328
Host                                 0
Year                                 0
home_goal                           96
away_goal                          148
home_goal_long                      96
away_goal_long                     148
home_own_goal                      330
away_own_goal                      335
home_penalty_goal                  294
away_penalty_goal                  313
home_penalty_miss_long             335
away_penalty_miss_long             341
home_penalty_shootout_goal_long    337
away_penalty_shootout_goal_long    337
home_penalty_shootout_miss_long    340
away_penalty_shootout_miss_long    338
home_red_card                      340
away_red_card                      337
home_yellow_red_card               340
away_yellow_red_card               345
home_yellow_card_long              135
away_yellow_card_long              118
home_substitute_in_long              4
away_substitute_in_long              5
dtype: int64

In [16]:
print(f"Valores duplicados en Wc:\n{wc.duplicated().sum()}")
print('\n')
print(f"Valores duplicados en Matches:\n{matches.duplicated().sum()}")

Valores duplicados en Wc:
0


Valores duplicados en Matches:
0

In [17]:
print(f"Tipos de datos en Wc:\n{wc.dtypes}")
print('\n')
print(f"Tipos de datos en Matches:\n{matches.dtypes}")

Tipos de datos en Wc:
Year              int64
Host             object
Teams             int64
Champion         object
Runner-Up        object
TopScorrer       object
Attendance        int64
AttendanceAvg     int64
Matches           int64
dtype: object


Tipos de datos en Matches:
home_team                           object
away_team                           object
home_score                           int64
home_xg                            float64
home_penalty                       float64
away_score                           int64
away_xg                            float64
away_penalty                       float64
home_manager                        object
home_captain                        object
away_manager                        object
away_captain                        object
Attendance                           int64
Venue                               object
Officials                           object
Round                               object
Date                                object
Score                               object
Referee                             object
Notes                               object
Host                                object
Year                                 int64
home_goal                           object
away_goal                           object
home_goal_long                      object
away_goal_long                      object
home_own_goal                       object
away_own_goal                       object
home_penalty_goal                   object
away_penalty_goal                   object
home_penalty_miss_long              object
away_penalty_miss_long              object
home_penalty_shootout_goal_long     object
away_penalty_shootout_goal_long     object
home_penalty_shootout_miss_long     object
away_penalty_shootout_miss_long     object
home_red_card                       object
away_red_card                       object
home_yellow_red_card                object
away_yellow_red_card                object
home_yellow_card_long               object
away_yellow_card_long               object
home_substitute_in_long             object
away_substitute_in_long             object
dtype: object

Así mismo, los campos que se relacionan entre ambas tablas son el año de realización del mundial (Variable `Year` en ambos dataframes) y el país anfitrión del torneo (Variable `Host` en ambos dataframes). En ninguno de los dos dataframes hay valores faltantes en estas variables.

Pasemos ahora con los análisis solicitados.

## 1.3 Tabla de posiciones del mundial 1991

Elabore la tabla de posiciones del mundial realizado en 1991. Tenga en cuenta que cada partido ganado da 3 puntos, cada partido empatado da 1 punto. Así mismo, las tarjetas amarillas suman -1 punto para juego limpio y las tarjetas rojas – 2 puntos a juego limpio.
La tabla debe tener la siguiente estructura:


Equipo | Partidos Jugados (PJ) | Partidos Ganados (PG) | Partidos Empatados (PE) | Partidos Perdidos (PP)| Goles a Favor (GF) |
Goles en Contra (GC) | Diferencia de Goles (GF – GC) | Juego Limpio (JL) | Puntos

Una cosa a tener en cuenta es que para el año 1991 las victorias en el fútbol otorgaban 2 puntos y no 3 como en la actualidad, sin embargo, como se solicitó que cada partido ganado dé 3 puntos, en este código se procederá con ese valor para el cálculo de la tabla.

Para el desarrollo de este punto, tuve que crear nuevas variables binarias que indican si el equipo local o visitante ganó, empató o perdió el encuentro, esto a partir de las variables `home_score` y `away_score` que juntas indican el marcador final del partido. A partir de estas nuevas variables se calcula cuantos puntos ganó el equipo local, y cuantos puntos ganó el equipo visitante.

Además, se filtró el dataframe `matches` para usar únicamente las variables necesarias en el año 1991.

In [24]:
wc1991=matches.loc[matches['Year']==1991, ['home_team', 'away_team', 'home_score', 'away_score', 'home_red_card', 'away_red_card', 'home_yellow_card_long', 'away_yellow_card_long', 'Round']]
wc1991['home_win']  = (wc1991['home_score'] >  wc1991['away_score']).astype(int)
wc1991['home_draw'] = (wc1991['home_score'] == wc1991['away_score']).astype(int)
wc1991['home_loss'] = (wc1991['home_score'] <  wc1991['away_score']).astype(int)
wc1991['home_points'] = wc1991['home_win']*3 + wc1991['home_draw']
wc1991['away_win']  = (wc1991['away_score'] >  wc1991['home_score']).astype(int)
wc1991['away_draw'] = (wc1991['away_score'] == wc1991['home_score']).astype(int)
wc1991['away_loss'] = (wc1991['away_score'] <  wc1991['home_score']).astype(int)
wc1991['away_points'] = wc1991['away_win']*3 + wc1991['away_draw']

Luego se realizó una codificación de la fase en la que se disputó el partido, esto con el objetivo de usarla para organizar la tabla final, debido a que, puede pasar que el equipo que quede campeón del torneo no sea el que más puntos haya hecho, pero al ser el ganador tiene que ser el primer lugar de la tabla, así como el segundo, tercer y cuarto puesto que se definen por partidos únicos, aunque en general no sean los de mayor puntaje, son los que ocupan esos lugares por el formato del torneo, por lo que la máxima ronda que hayan alcanzado a disputar y su desempeño en esta será lo que determine su lugar en la tabla.

In [ ]:
wc1991['Round']= wc1991['Round'].replace({
    'Group stage': 0,
    'Quarter-finals': 1,
    'Semi-finals': 2,
    'Third-place match': 3,
    'Final': 4
})

Debido a cómo se encontraban registradas las jugadoras amonestadas en el dataset, se tuvo que hacer una limpieza para poder saber cuantas eran las amonestaciones por partido y por equipo.

In [26]:
cols=['home_yellow_card_long', 'away_yellow_card_long', 'home_red_card', 'away_red_card']
for col in cols:
    wc1991[col]=wc1991[col].str.split(',').str.len().fillna(0).astype(int)

C:\Users\Hector\AppData\Local\Temp\ipykernel_22336\2026717759.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  wc1991[col]=wc1991[col].str.split(',').str.len().fillna(0).astype(int)

Finalmente, dado que la misma seleccion podía oficiar en el registro del partido como local o visitante debido a que el torneo se realiza en territorio neutral, se separa el dataframe en local y visitante para luego concatenarse de nuevo en uno solo y así poder hacer las agrupaciones por equipo necesarias y solicitadas.

In [ ]:

home = wc1991[['home_team', 'home_score', 'away_score',
                     'home_win', 'home_draw', 'home_loss', 'home_points', 'Round', 'home_red_card', 'home_yellow_card_long']].copy()
home.columns = ['team', 'gf', 'gc', 'win', 'draw', 'loss', 'points', 'Round', 'red_card', 'yellow_card']


away = wc1991[['away_team', 'away_score', 'home_score',
                     'away_win', 'away_draw', 'away_loss', 'away_points', 'Round', 'away_red_card', 'away_yellow_card_long']].copy()
away.columns = ['team', 'gf', 'gc', 'win', 'draw', 'loss', 'points', 'Round', 'red_card', 'yellow_card']


all_matches = pd.concat([home, away], ignore_index=True)


standings = all_matches.groupby('team').agg(
    PJ  = ('team',   'count'),
    PG  = ('win',    'sum'),
    PE  = ('draw',   'sum'),
    PP  = ('loss',   'sum'),
    GF  = ('gf',     'sum'),
    GC  = ('gc',     'sum'),
    round = ('Round', 'max'),
    yellow=('yellow_card', 'sum'),
    red=('red_card', 'sum'),
    PTS = ('points', 'sum')

).reset_index()

standings['DG'] = standings['GF'] - standings['GC']
standings['JL'] = -standings['yellow'] -2 * standings['red']
standings['PTS'] = standings.pop('PTS')

standings =standings.sort_values(
    by       = ['round', 'PTS', 'DG', 'GF'],
    ascending= [False, False,False, False]
).reset_index(drop=True)
standings.index += 1

print(standings.drop(columns=['round', 'yellow', 'red']).to_markdown())

|    | team           |   PJ |   PG |   PE |   PP |   GF |   GC |   DG |   JL |   PTS |
|---:|:---------------|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|------:|
|  1 | United States  |    6 |    6 |    0 |    0 |   25 |    5 |   20 |   -4 |    18 |
|  2 | Norway         |    6 |    4 |    0 |    2 |   14 |   10 |    4 |   -4 |    12 |
|  3 | Sweden         |    6 |    4 |    0 |    2 |   18 |    7 |   11 |   -6 |    12 |
|  4 | Germany        |    6 |    4 |    0 |    2 |   13 |   10 |    3 |   -3 |    12 |
|  5 | China PR       |    4 |    2 |    1 |    1 |   10 |    4 |    6 |   -2 |     7 |
|  6 | Italy          |    4 |    2 |    0 |    2 |    8 |    5 |    3 |   -3 |     6 |
|  7 | Denmark        |    4 |    1 |    1 |    2 |    7 |    6 |    1 |   -2 |     4 |
|  8 | Chinese Taipei |    4 |    1 |    0 |    3 |    2 |   15 |  -13 |   -3 |     3 |
|  9 | Brazil         |    3 |    1 |    0 |    2 |    1 |    7 |   -6 |   -4 |     3 |
| 10 | Nigeria        |    3 |    0 |    0 |    3 |    0 |    7 |   -7 |   -2 |     0 |
| 11 | New Zealand    |    3 |    0 |    0 |    3 |    1 |   11 |  -10 |    0 |     0 |
| 12 | Japan          |    3 |    0 |    0 |    3 |    0 |   12 |  -12 |   -1 |     0 |

## 1.4 Tabla de goleadoras del mundial 2023

Aquí nuevamente se filtró por el año 2023 el dataframe `matches`, y además conservando solamente las variables correspondientes a goles marcados en tiempo regular, ya sean hechos en jugada, de penal, o autogoles. Los goles en tanda de penales no cuentan en el registro oficial de la FIFA como goles para contabilizar en la tabla de goleadoras, así que aunque se contaba con esa variable, no será tomada en cuenta para el análisis.

In [18]:
wc2023=matches.loc[matches['Year']==2023, ['home_goal', 'away_goal', 'home_own_goal', 'away_own_goal','home_penalty_goal', 'away_penalty_goal']]

In [19]:
wc2023.head()

,home_goal,away_goal,home_own_goal,away_own_goal,home_penalty_goal,away_penalty_goal
0,Olga Carmona · 29’,NaN,NaN,NaN,NaN,NaN
1,Kosovare Asllani · 62’,NaN,NaN,NaN,Fridolina Rolfö (P) · 30’,NaN
2,Sam Kerr · 63’,Ella Toone · 36’|Lauren Hemp · 71’|Alessia Rus...,NaN,NaN,NaN,NaN
3,Salma Paralluelo · 81’|Olga Carmona · 89’,Rebecka Blomqvist · 88’,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN

Aquí se tuvo que hacer un preprocesamiento nuevamente debido a como se registran los goles en las variables disponibles.

In [30]:
cols= wc2023.columns
for col in cols:
    wc2023[col] = wc2023[col].str.split('|')

In [32]:
import numpy as np
for col in cols:
    for i in range(len(wc2023)):
        if wc2023[col].iloc[i] is not np.nan:
            n=len(wc2023[col].iloc[i])
            for j in range(n):
                wc2023[col].iloc[i][j] = wc2023[col].iloc[i][j].split(' ·')[0].split(' (P)')[0].strip()

Luego, se utiliza la función `Counter` de la librería `collections` para contar el número de goles marcados por cada jugadora. Los goles de penal en el tiempo reglamentario también cuentan para esta tabla, mientras que todos los autogoles marcados en el torneo decidí contarlos todos como un solo jugador ya que estos no corresponden como goles a favor del equipo de la persona que metió el autogol.

In [34]:
from collections import Counter

contador = Counter()
goal_cols=['home_goal', 'away_goal','home_penalty_goal', 'away_penalty_goal']
for col in goal_cols:
    for i in range(len(wc2023)):
        if wc2023[col].iloc[i] is not np.nan:
            contador.update(wc2023[col].iloc[i])
            
for col in ['home_own_goal', 'away_own_goal']:
    for i in range(len(wc2023)):
        if wc2023[col].iloc[i] is not np.nan:
            contador.update({'Autogol': len(wc2023[col].iloc[i])})

In [39]:
goles = (pd.DataFrame.from_dict(contador, orient='index', columns=['Goles'])
           .reset_index()
           .rename(columns={'index': 'Jugadora'})
           .sort_values('Goles', ascending=False)).reset_index(drop=True)

print(goles)

             Jugadora  Goles
0             Autogol      8
1     Hinata Miyazawa      5
2    Kadidiatou Diani      4
3      Alexandra Popp      4
4     Amanda Ilestedt      4
..                ...    ...
96       Leicy Santos      1
97        Laia Codina      1
98         Kenza Dali      1
99    Melissa Herrera      1
100        Klara Bühl      1

[101 rows x 2 columns]

## 1.5 Tabla general

Finalmente, se solicitó una tabla general que muestre:

Año | Host | Equipo | Partidos Jugados | Goles Totales marcados | Promedio de Goles marcados | Goles Totales recibidos | promedio
de goles recibidos | partidos totales ganados | partidos totales perdidos | partidos totales empatados | promedio de asistencia por
equipo.

Para esta tabla se procede de la misma manera que en la tabla de 1991 en el sentido de la creación de variables y la concatenación de los dataframes creados.

In [ ]:
table= matches[['Year', 'Host','home_team', 'away_team', 'home_score', 'away_score', 'Attendance']]
table['home_win']  = (table['home_score'] >  table['away_score']).astype(int)
table['home_draw'] = (table['home_score'] == table['away_score']).astype(int)
table['home_loss'] = (table['home_score'] <  table['away_score']).astype(int)
table['away_win']  = (table['away_score'] >  table['home_score']).astype(int)
table['away_draw'] = (table['away_score'] == table['home_score']).astype(int)
table['away_loss'] = (table['away_score'] <  table['home_score']).astype(int)

In [42]:
table.head()

,Year,Host,home_team,away_team,home_score,away_score,Attendance,home_win,home_draw,home_loss,away_win,away_draw,away_loss
0,2023,"Australia, New Zealand",Spain,England,1,0,75784,1,0,0,0,0,1
1,2023,"Australia, New Zealand",Sweden,Australia,2,0,49461,1,0,0,0,0,1
2,2023,"Australia, New Zealand",Australia,England,1,3,75784,0,0,1,1,0,0
3,2023,"Australia, New Zealand",Spain,Sweden,2,1,43217,1,0,0,0,0,1
4,2023,"Australia, New Zealand",Australia,France,0,0,49461,0,1,0,0,1,0

In [ ]:


home = table[['Year','Host','Attendance','home_team', 'home_score', 'away_score',
                     'home_win', 'home_draw', 'home_loss']].copy()
home.columns = ['year', 'host', 'attendance', 'team', 'gf', 'gc', 'win', 'draw', 'loss']


away = table[['Year','Host','Attendance','away_team', 'away_score', 'home_score',
                     'away_win', 'away_draw', 'away_loss']].copy()
away.columns = ['year', 'host', 'attendance', 'team', 'gf', 'gc', 'win', 'draw', 'loss']


matches_concat = pd.concat([home, away], ignore_index=True)


standings = matches_concat.groupby(['year', 'host', 'team']).agg(
    PJ  = ('team',   'count'),
    GF  = ('gf',     'sum'),
    GC  = ('gc',     'sum'),
    PG  = ('win',    'sum'),
    PE  = ('draw',   'sum'),
    PP  = ('loss',   'sum'),
    Attendance = ('attendance', 'sum')
).round(2).reset_index()

standings['AVG_GF']   = (standings['GF']  / standings['PJ']).round(2)
standings['AVG_GC']  = (standings['GC'] / standings['PJ']).round(2)
standings['AVG_Attendance'] = (standings['Attendance']/ standings['PJ']).round(0).astype(int)

In [26]:
standings.sort_values(by=['year','team'], ascending=[False,True]).drop(columns=['Attendance']).reset_index(drop=True)

,year,host,team,PJ,GF,GC,PG,PE,PP,AVG_GF,AVG_GC,AVG_Attendance
0,2023,"Australia, New Zealand",Argentina,3,2,5,0,1,2,0.67,1.67,19210
1,2023,"Australia, New Zealand",Australia,7,10,8,3,1,3,1.43,1.14,57591
2,2023,"Australia, New Zealand",Brazil,3,5,2,1,1,1,1.67,0.67,30053
3,2023,"Australia, New Zealand",Canada,3,2,5,1,1,1,0.67,1.67,22060
4,2023,"Australia, New Zealand",China PR,3,2,7,1,0,2,0.67,2.33,14387
...,...,...,...,...,...,...,...,...,...,...,...,...
163,1991,China PR,New Zealand,3,1,11,0,0,3,0.33,3.67,13333
164,1991,China PR,Nigeria,3,0,7,0,0,3,0.00,2.33,13333
165,1991,China PR,Norway,6,14,10,4,0,2,2.33,1.67,30750
166,1991,China PR,Sweden,6,18,7,4,0,2,3.00,1.17,21833
167,1991,China PR,United States,6,25,5,6,0,0,4.17,0.83,23083